name: flutter3_startup_project
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  cloud_firestore: ^3.5.0
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  easy_localization: ^3.0.1
  equatable: ^2.0.5
  firebase_auth: ^3.11.0
  firebase_core: ^1.24.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  location: ^4.4.0
  shared_preferences: ^2.0.15
  sizer: ^2.0.15
  socket_io_client: ^1.0.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/translations/
    - assets/icons/
